version: '3.8'
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  coqui-tts:
    build:
      context: .
      dockerfile: Dockerfile.tts
    container_name: coqui-tts
    ports:
      - "5002:5002"
    volumes:
      - coqui_data:/root/.local/share/tts
    restart: unless-stopped
    environment:
      - MODEL_NAME=tts_models/en/ljspeech/tacotron2-DDC
      - USE_CPU=true

volumes:
  ollama_data:
  coqui_data: 