# Speech-to-Text Configuration
model_path: "models/whisper-tiny.en"  # Path to the Whisper model
language: "en"                         # Language for speech recognition
device: "cuda"                         # Device to use (cuda or cpu)

# Audio Settings
sample_rate: 16000                     # Audio sample rate
chunk_size: 1024                       # Size of audio chunks to process
max_silence: 1.0                       # Maximum silence duration in seconds

# Recognition Settings
min_confidence: 0.5                    # Minimum confidence threshold
max_length: 30                         # Maximum length of recognized text 